name: pdfmerge
version: 1.1.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.6
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: 4.6.6
  path_provider: ^2.1.2
  syncfusion_flutter_pdf: ^24.2.9
  syncfusion_flutter_pdfviewer: ^24.2.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  msix: ^3.16.7

flutter:
  uses-material-design: true

msix_config:
  display_name: PDFPermission
  msix_version: 1.1.0.0
  install_certificate: false
